# Generated by Django 5.1.4 on 2024-12-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, verbose_name='Активно ли объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Год постройки здания'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(help_text='Первый этаж, последний этаж, пятый этаж', max_length=20, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, null=True, verbose_name='Наличие балкона'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Количество жилых кв.метров'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Цена квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Количество комнат в квартире'),
        ),
    ]
