# Generated by Django 2.2.24 on 2024-12-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_active_alter_flat_construction_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
