# Generated by Django 2.2.24 on 2024-12-23 12:04

from django.db import migrations
import phonenumbers


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(pure_phone):
            flat.owner_pure_phone = phonenumbers.format_number(pure_phone,
                                                               phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20241223_1456'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber),
    ]
