# Generated by Django 2.2.24 on 2024-12-23 14:49

from django.db import migrations


def fill_db_owner(apps, schema_editor):
    Flats = apps.get_model('property',
                           'Flat')
    Owner = apps.get_model('property',
                           'Owner')
    for flat in Flats.objects.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_pure_phone,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(fill_db_owner)
    ]
