# Generated by Django 2.2.24 on 2024-12-23 19:52

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20241223_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО владельца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='who_liked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='owner_flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
