# Generated by Django 2.2.24 on 2024-12-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20241228_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_name',
            new_name='user',
        ),
    ]
